/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

int main(void)
{
    /* Loop forever */
	uint8_t a = 200; /*aqui se observa en el depurador un 200*/
    int8_t b = 200; /*aqui observaremos un valor diferente ya que la variable es un entero de bit lo que el bit mas significativo indica el signo aqui seria -56*/
    int8_t c = -1; /*observamos que en hexdecimal seria 0xFF*/
    while(1){}
    

}
