/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

int main(void)
{
    /* Loop forever */
	int8_t x = 127; /*aqui lo que sucede es un overflow o desbordamiento ya que el bit de la izquierda es el mas significativo lo que nos muestra en el depurador al sumarle un 1 nos muestra el limite negaivo que seria -128 */
    x= x + 1;
    uint8_t y = 255; /*aqui pasa un desbordamiento sin signo ya que el bit esta configurado de 0 a 255 lo que sucede al sumarle el 1 es que idealmente quedaria un 100000000 pero al limitar la arquitectura a 8 bit el 1 de la izquierda desaparece y queda un 00000000 dadno un cero en el depurador*/
    y = y + 1;
    while(1){}
    

}
