/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

int main(void)
{   
    uint8_t x = 200;
    uint8_t y = 100;
    uint8_t sum = x + y;
    /*En este ejercicio vemos como el desbordamiento al hacer la suma queda un noveno bit con un valor que no toma en cuenta ya que estamos en 8 bits la suma de 01100100 (100) + 11001000 (200) el resultado seria 100101100 pero al haber nueve bits el de mas a la izquierda se pierde quedando 00101100 que da un resultado de 44*/

    while(1){}
  

}
